import type { Theme, ThemeTokens } from '@/themes/types'

export const kanagawaPalette = {
  sumiInk0: '#16161D',
  sumiInk1: '#181820',
  sumiInk2: '#1a1a22',
  sumiInk3: '#1F1F28',
  sumiInk4: '#2A2A37',
  sumiInk5: '#363646',
  sumiInk6: '#54546D',
  waveBlue1: '#223249',
  waveBlue2: '#2D4F67',
  autumnGreen: '#76946A',
  autumnRed: '#C34043',
  autumnYellow: '#DCA561',
  samuraiRed: '#E82424',
  roninYellow: '#FF9E3B',
  waveAqua1: '#6A9589',
  dragonBlue: '#658594',
  oldWhite: '#C8C093',
  fujiWhite: '#DCD7BA',
  fujiGray: '#727169',
  oniViolet: '#957FB8',
  oniViolet2: '#b8b4d0',
  crystalBlue: '#7E9CD8',
  springViolet1: '#938AA9',
  springViolet2: '#9CABCA',
  springBlue: '#7FB4CA',
  waveAqua2: '#7AA89F',
  springGreen: '#98BB6C',
  boatYellow1: '#938056',
  boatYellow2: '#C0A36E',
  carpYellow: '#E6C384',
  sakuraPink: '#D27E99',
  waveRed: '#E46876',
  peachRed: '#FF5D62',
  surimiOrange: '#FFA066',
  katanaGray: '#717C7C',
  dragonBlack0: '#0d0c0c',
  dragonBlack1: '#12120f',
  dragonBlack2: '#1D1C19',
  dragonBlack3: '#181616',
  dragonBlack4: '#282727',
  dragonBlack5: '#393836',
  dragonBlack6: '#625e5a',
  dragonWhite: '#c5c9c5',
  dragonGreen: '#87a987',
  dragonGreen2: '#8a9a7b',
  dragonPink: '#a292a3',
  dragonOrange: '#b6927b',
  dragonGray: '#a6a69c',
  dragonGray2: '#9e9b93',
  dragonGray3: '#7a8382',
  dragonBlue2: '#8ba4b0',
  dragonViolet: '#8992a7',
  dragonRed: '#c4746e',
  dragonAqua: '#8ea4a2',
  dragonAsh: '#737c73',
  dragonTeal: '#949fb5',
  dragonYellow: '#c4b28a',
  lotusInk1: '#545464',
  lotusInk2: '#43436c',
  lotusGray: '#dcd7ba',
  lotusGray2: '#716e61',
  lotusGray3: '#8a8980',
  lotusWhite0: '#d5cea3',
  lotusWhite1: '#dcd5ac',
  lotusWhite2: '#e5ddb0',
  lotusWhite3: '#f2ecbc',
  lotusWhite4: '#e7dba0',
  lotusWhite5: '#e4d794',
  lotusViolet1: '#a09cac',
  lotusViolet2: '#766b90',
  lotusViolet3: '#c9cbd1',
  lotusViolet4: '#624c83',
  lotusBlue1: '#c7d7e0',
  lotusBlue2: '#b5cbd2',
  lotusBlue3: '#9fb5c9',
  lotusBlue4: '#4d699b',
  lotusBlue5: '#5d57a3',
  lotusGreen: '#6f894e',
  lotusGreen2: '#6e915f',
  lotusPink: '#b35b79',
  lotusOrange: '#cc6d00',
  lotusOrange2: '#e98a00',
  lotusYellow: '#77713f',
  lotusYellow2: '#836f4a',
  lotusRed: '#c84053',
  lotusRed2: '#d7474b',
  lotusRed3: '#e82424',
  lotusAqua: '#597b75',
  lotusAqua2: '#5e857a',
  lotusTeal1: '#4e8ca2',
  lotusTeal2: '#6693bf',
  lotusTeal3: '#5a7785',
} as const

const translucent = (color: string, amount: number) => `color-mix(in srgb, ${color} ${amount}%, transparent)`

const waveTokens: ThemeTokens = {
  canvas: kanagawaPalette.sumiInk3,
  sidebar: kanagawaPalette.sumiInk1,
  surface: kanagawaPalette.sumiInk4,
  surfaceElevated: kanagawaPalette.sumiInk5,
  surfaceSelected: kanagawaPalette.waveBlue1,
  surfaceHover: kanagawaPalette.sumiInk5,
  viewport: kanagawaPalette.sumiInk0,
  overlay: kanagawaPalette.sumiInk0,
  border: kanagawaPalette.sumiInk6,
  text: kanagawaPalette.fujiWhite,
  textBody: kanagawaPalette.oldWhite,
  textMuted: kanagawaPalette.fujiGray,
  textQuiet: kanagawaPalette.sumiInk6,
  accent: kanagawaPalette.crystalBlue,
  accentHover: kanagawaPalette.springBlue,
  accentForeground: kanagawaPalette.sumiInk0,
  ink: kanagawaPalette.sumiInk0,
  success: kanagawaPalette.springGreen,
  warning: kanagawaPalette.boatYellow2,
  error: kanagawaPalette.waveRed,
  info: kanagawaPalette.waveAqua2,
  shadowColor: translucent(kanagawaPalette.sumiInk0, 72),
}

const dragonTokens: ThemeTokens = {
  canvas: kanagawaPalette.dragonBlack3,
  sidebar: kanagawaPalette.dragonBlack1,
  surface: kanagawaPalette.dragonBlack4,
  surfaceElevated: kanagawaPalette.dragonBlack5,
  surfaceSelected: kanagawaPalette.waveBlue1,
  surfaceHover: kanagawaPalette.dragonBlack5,
  viewport: kanagawaPalette.dragonBlack0,
  overlay: kanagawaPalette.dragonBlack0,
  border: kanagawaPalette.dragonBlack6,
  text: kanagawaPalette.dragonWhite,
  textBody: kanagawaPalette.dragonGray,
  textMuted: kanagawaPalette.dragonGray3,
  textQuiet: kanagawaPalette.dragonAsh,
  accent: kanagawaPalette.dragonBlue2,
  accentHover: kanagawaPalette.dragonTeal,
  accentForeground: kanagawaPalette.dragonBlack0,
  ink: kanagawaPalette.dragonBlack0,
  success: kanagawaPalette.dragonGreen,
  warning: kanagawaPalette.dragonYellow,
  error: kanagawaPalette.dragonRed,
  info: kanagawaPalette.dragonAqua,
  shadowColor: translucent(kanagawaPalette.dragonBlack0, 76),
}

const lotusTokens: ThemeTokens = {
  canvas: kanagawaPalette.lotusWhite3,
  sidebar: kanagawaPalette.lotusWhite1,
  surface: kanagawaPalette.lotusWhite2,
  surfaceElevated: kanagawaPalette.lotusWhite0,
  surfaceSelected: kanagawaPalette.lotusViolet3,
  surfaceHover: kanagawaPalette.lotusWhite0,
  viewport: kanagawaPalette.lotusWhite5,
  overlay: kanagawaPalette.lotusInk1,
  border: kanagawaPalette.lotusGray2,
  text: kanagawaPalette.lotusInk1,
  textBody: kanagawaPalette.lotusInk2,
  textMuted: kanagawaPalette.lotusGray2,
  textQuiet: kanagawaPalette.lotusGray3,
  accent: kanagawaPalette.lotusBlue4,
  accentHover: kanagawaPalette.lotusBlue5,
  accentForeground: kanagawaPalette.lotusWhite3,
  ink: kanagawaPalette.lotusWhite3,
  success: kanagawaPalette.lotusGreen,
  warning: kanagawaPalette.lotusOrange,
  error: kanagawaPalette.lotusRed,
  info: kanagawaPalette.lotusTeal1,
  shadowColor: translucent(kanagawaPalette.lotusInk1, 24),
}

export const createKanagawaTheme = (id: Theme['id'], name: string, isDark: boolean, tokens: ThemeTokens): Theme => ({
  id,
  packId: 'kanagawa',
  packName: 'Kanagawa',
  name,
  isDark,
  tokens,
})

export { dragonTokens, lotusTokens, waveTokens }
